# --------------------------
# Docker Compose Override for Local Development
# --------------------------
# This file extends/overrides the main docker-compose.yml
# It's automatically loaded by Docker Compose when it exists
# Used for development-specific configurations

services:
  # --------------------------
  # App container overrides
  # --------------------------
  app:
    environment:
      - APP_ENV=development
      - APP_DEBUG=true

    volumes:
      - ./src:/var/www/html

    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        INSTALL_XDEBUG: true

  # --------------------------
  # Queue worker for Laravel jobs
  # --------------------------
  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: ${PROJECT_NAME}-queue

    # Wait for MySQL before starting queue worker
    command: >
      sh -c "until nc -z ${PROJECT_NAME}-mysql 3306;
      do echo '⏳ Waiting for MySQL...';
      sleep 3;
      done;
      php artisan queue:work --verbose --tries=3 --timeout=90"

    volumes:
      - ./src:/var/www/html

    environment:
      APP_ENV: development
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: ${PROJECT_NAME}-mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy

    restart: on-failure

    networks:
      - breeze-theme

  # --------------------------
  # Scheduler for Laravel cron jobs
  # --------------------------
  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: ${PROJECT_NAME}-scheduler

    # Wait for MySQL before starting scheduler
    command: >
      sh -c "until nc -z ${PROJECT_NAME}-mysql 3306;
      do echo '⏳ Waiting for MySQL...';
      sleep 3;
      done;
      while true;
      do php artisan schedule:run --verbose --no-interaction;
      sleep 60;
      done"

    volumes:
      - ./src:/var/www/html

    environment:
      APP_ENV: development
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: ${PROJECT_NAME}-mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}

    depends_on:
      mysql:
        condition: service_healthy

    restart: on-failure

    networks:
      - breeze-theme

# --------------------------
# Networks
# --------------------------
networks:
  breeze-theme:
    name: ${PROJECT_NAME}
    driver: bridge
